Tesnig the data-v2 code.

diff --git a/src/polap-data-taxon b/src/polap-data-taxon
--- a/src/polap-data-taxon
+++ b/src/polap-data-taxon
@@ -15,8 +15,14 @@
 # polap. If not, see <https://www.gnu.org/licenses/>.
 ################################################################################
 
-DEBUG=0
-_POLAP_RELEASE=1
+if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
+  echo "[ERROR] This script must be executed, not sourced: use 'bash $BASH_SOURCE'" >&2
+  return 1 2>/dev/null || exit 1
+fi
+: "${_POLAP_DEBUG:=0}"
+export _POLAP_DEBUG
+: "${_POLAP_RELEASE:=1}"
+export _POLAP_RELEASE
 
 # Taxonomy
 #
