Update bash variables: _POLAP_DEBUG and _POLAP_RELEASE.
disassemble.R -> index=-1, n=1 when only one candidate remains.

diff --git a/src/polap b/src/polap
--- a/src/polap
+++ b/src/polap
@@ -30,8 +30,8 @@
 # _POLAP_DEBUG=0
 # _POLAP_RELEASE=0
 if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
-  echo "[ERROR] This script must be executed, not sourced: use 'bash $BASH_SOURCE'" >&2
-  return 1 2>/dev/null || exit 1
+	echo "[ERROR] This script must be executed, not sourced: use 'bash $BASH_SOURCE'" >&2
+	return 1 2>/dev/null || exit 1
 fi
 : "${_POLAP_DEBUG:=0}"
 export _POLAP_DEBUG
@@ -40,8 +40,8 @@ export _POLAP_RELEASE
 
 # OTHER STUFF GENERATED BY Argbash
 _polap_script_bin_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || {
-  echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2
-  exit 2
+	echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2
+	exit 2
 }
 _POLAPLIB_DIR="${_polap_script_bin_dir}/polaplib"
 source "${_POLAPLIB_DIR}/polap-git-hash-version.sh"
@@ -132,6 +132,8 @@ source "${_POLAPLIB_DIR}/run-polap-function-demo.sh"
 source "${_POLAPLIB_DIR}/run-polap-function-ncbixml.sh"
 source "${_POLAPLIB_DIR}/run-polap-function-config.sh"
 
+source "${_POLAPLIB_DIR}/polap-cmd-ptgaul.sh"
+
 ################################################################################
 # All of the variables at our disposal
 ################################################################################
@@ -140,9 +142,9 @@ source "${_POLAPLIB_DIR}/run-polap-function-config.sh"
 # MAIN
 #
 if [ $# -eq 0 ]; then
-  print_help
-  touch make-menus
-  exit $EXIT_SUCCESS
+	print_help
+	touch make-menus
+	exit $EXIT_SUCCESS
 fi
 
 # the default output o is created.
@@ -162,23 +164,23 @@ echo "CMD: $CMD"
 
 # Print all the global variables from polap-parsing.sh.
 for var in $(compgen -v _arg_); do
-  echo "$var=${!var}"
+	echo "$var=${!var}"
 done
 
 # Call a subcommand function
 if declare -f "_run_polap_${_arg_menu[0]}" >/dev/null 2>&1; then
-  # invoke that function, passing arguments through
-  # _run_polap_"$@" # same as "$1" "$2" "$3" ... for full argument list
-  if _run_polap_${_arg_menu[0]}; then
-    _polap_log3 "Menu ${_arg_menu[0]} has been finished."
-  else
-    _polap_error_message $?
-  fi
+	# invoke that function, passing arguments through
+	# _run_polap_"$@" # same as "$1" "$2" "$3" ... for full argument list
+	if _run_polap_${_arg_menu[0]}; then
+		_polap_log3 "Menu ${_arg_menu[0]} has been finished."
+	else
+		_polap_error_message $?
+	fi
 else
-  _polap_log0 "Menu: assemble, prepare-polishing, polish"
-  _polap_log0 "  assemble1, total-length-long, find-genome-size, reduce-data, flye1, annotate"
-  _polap_log0 "  assemble2, select-seeds, map-reads, test-reads, select-reads, flye2"
-  _polap_log0 "ERROR: no such menu of $1"
+	_polap_log0 "Menu: assemble, prepare-polishing, polish"
+	_polap_log0 "  assemble1, total-length-long, find-genome-size, reduce-data, flye1, annotate"
+	_polap_log0 "  assemble2, select-seeds, map-reads, test-reads, select-reads, flye2"
+	_polap_log0 "ERROR: no such menu of $1"
 fi
 
 [[ "${_arg_clock}" == "on" ]] && date +"%Y-%m-%d %H:%M:%S" >&3
